# Generated by Django 5.2.7 on 2025-11-11 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('passport', models.CharField(max_length=30, unique=True)),
                ('is_military', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_kid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=30, unique=True)),
                ('begin_point', models.CharField(max_length=50)),
                ('end_point', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['train_number'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('PL', 'Plazkart'), ('KP', 'Kupe'), ('LX', 'Lux')], default='PL', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.passenger')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.train')),
            ],
            options={
                'ordering': ['-date_purchased'],
            },
        ),
    ]
